export const ListSyllabus = [
    {label: "BIEAP"},
    {label: "BSEAP"},
    {label: "BSEB"},
    {label: "BSEH"},
    {label: "CBSE"},
    {label: "CGBSE"},
    {label: "GSEB"},
    {label: "HBSE"},
    {label: "HPBOSE"},
    {label: "IB"},
    {label: "ICSE"},
    {label: "IGCSE"},
    {label: "ISC"},
    {label: "JKBOSE"},
    {label: "KSEEB"},
    {label: "MPBSE"},
    {label: "MSBSHSE"},
    {label: "NIOS"},
    {label: "PSEB"},
    {label: "RBSE"},
    {label: "TBSE"},
    {label: "WBBSE"},
    {label: "WBCHSE"},
    {label: "UP BOARD"},
    {label: "SAMACHEER"},
]

export const ListGrade = [
    {label: "1"},
    {label: "2"},
    {label: "3"},
    {label: "4"},
    {label: "5"},
    {label: "6"},
    {label: "7"},
    {label: "8"},
    {label: "9"},
    {label: "10"},
    {label: "11"},
    {label: "12"},
]

export const ListGender = [
    {label: "Male"},
    {label: "Female"},
]